[package]
name = "telegram-capture-bot"
version = "0.1.0"
authors = ["Zoran Zaric <zz@zoranzaric.de>"]
edition = "2018"

[dependencies]
frankenstein = "0.3.1"
ureq = "2.1.1"

metrics = "^0.15"
metrics-util = "^0.7"
metrics-exporter-prometheus = "0.4"

tracing = "0.1"
tracing-subscriber = "0.2"
